package com.example.a501_03.app_class_portfolio_leejanghee0330.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.a501_03.app_class_portfolio_leejanghee0330.db.travel;
import com.example.a501_03.app_class_portfolio_leejanghee0330.db.Schedule;
import com.example.a501_03.app_class_portfolio_leejanghee0330.db.Place;

import com.example.a501_03.app_class_portfolio_leejanghee0330.db.travelDao;
import com.example.a501_03.app_class_portfolio_leejanghee0330.db.ScheduleDao;
import com.example.a501_03.app_class_portfolio_leejanghee0330.db.PlaceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig travelDaoConfig;
    private final DaoConfig scheduleDaoConfig;
    private final DaoConfig placeDaoConfig;

    private final travelDao travelDao;
    private final ScheduleDao scheduleDao;
    private final PlaceDao placeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        travelDaoConfig = daoConfigMap.get(travelDao.class).clone();
        travelDaoConfig.initIdentityScope(type);

        scheduleDaoConfig = daoConfigMap.get(ScheduleDao.class).clone();
        scheduleDaoConfig.initIdentityScope(type);

        placeDaoConfig = daoConfigMap.get(PlaceDao.class).clone();
        placeDaoConfig.initIdentityScope(type);

        travelDao = new travelDao(travelDaoConfig, this);
        scheduleDao = new ScheduleDao(scheduleDaoConfig, this);
        placeDao = new PlaceDao(placeDaoConfig, this);

        registerDao(travel.class, travelDao);
        registerDao(Schedule.class, scheduleDao);
        registerDao(Place.class, placeDao);
    }
    
    public void clear() {
        travelDaoConfig.clearIdentityScope();
        scheduleDaoConfig.clearIdentityScope();
        placeDaoConfig.clearIdentityScope();
    }

    public travelDao getTravelDao() {
        return travelDao;
    }

    public ScheduleDao getScheduleDao() {
        return scheduleDao;
    }

    public PlaceDao getPlaceDao() {
        return placeDao;
    }

}
